user nginx;

pid /run/nginx.pid;

worker_processes auto;

events {
    use                 epoll;
    worker_connections  2048;
    multi_accept        on;
}

error_log /dev/stdout error;

http {
    access_log /dev/stdout combined;
  

    server {
        listen 80;
        server_name mail.hack.club;
        add_header Server "redirectorizer";
        add_header X-Clacks-Overhead "GNU Terry Pratchett";
        return 301 https://mail.hackclub.com$request_uri;
    }
    
    server {
        listen 80;
        server_name hackclub.id;
        add_header Server "redirectorizer";
        add_header X-Clacks-Overhead "GNU Terry Pratchett";
        return 301 https://identity.hackclub.com$request_uri;
    }

    server {
        listen 80;
        server_name flagship.hack.club;
        add_header Server "redirectorizer";
        add_header X-Clacks-Overhead "GNU Terry Pratchett";
        return 301 https://flagship.hackclub.com$request_uri;
    }
}
